### ISSUE TITLE
ValueError: could not convert string to float: '1,006.7'

### ISSUE THREAD

**Issue by harshanas** [harshanas/Py1337x#1]
Code:
```python
from Py1337x import Py1337x
leechClient = Py1337x()
sr = leechClient.search("Silicon Valley S01E01")
```
Output:
```
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    sr = leechClient.search("Silicon Valley S01E01")
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\Py1337x\Py1337x.py", line 54, in search
    torrent_data = self.get_torrent_data(page_link, removeZeroSeeds)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\Py1337x\Py1337x.py", line 88, in get_torrent_data
    size_split[0] = float(size_split[0])
ValueError: could not convert string to float: '1,006.7'
```

**Comment by harshanas** [comment]
Fixes issue #1
